/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

/**
 *
 * @author PC3
 */
public class View_Mayor extends javax.swing.JFrame {

    /**
     * Creates new form View_Mayor
     */
    public View_Mayor() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jl_numero1 = new javax.swing.JLabel();
        jl_numero2 = new javax.swing.JLabel();
        jl_numero3 = new javax.swing.JLabel();
        jtf_numero1 = new javax.swing.JTextField();
        jtf_numero2 = new javax.swing.JTextField();
        jtf_numero3 = new javax.swing.JTextField();
        jbtn_calcular = new javax.swing.JButton();
        jl_mayor = new javax.swing.JLabel();
        jtf_mayor = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jl_numero1.setText("Numero1");
        getContentPane().add(jl_numero1, new org.netbeans.lib.awtextra.AbsoluteConstraints(46, 35, -1, -1));

        jl_numero2.setText("Numero2");
        getContentPane().add(jl_numero2, new org.netbeans.lib.awtextra.AbsoluteConstraints(46, 129, -1, -1));

        jl_numero3.setText("Numero3");
        getContentPane().add(jl_numero3, new org.netbeans.lib.awtextra.AbsoluteConstraints(46, 212, -1, -1));
        getContentPane().add(jtf_numero1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 30, 174, -1));
        getContentPane().add(jtf_numero2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 120, 174, -1));
        getContentPane().add(jtf_numero3, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 200, 174, -1));

        jbtn_calcular.setBackground(new java.awt.Color(102, 102, 255));
        jbtn_calcular.setText("Calcular");
        getContentPane().add(jbtn_calcular, new org.netbeans.lib.awtextra.AbsoluteConstraints(48, 260, 320, -1));

        jl_mayor.setText("Numero Mayor");
        getContentPane().add(jl_mayor, new org.netbeans.lib.awtextra.AbsoluteConstraints(46, 317, -1, -1));
        getContentPane().add(jtf_mayor, new org.netbeans.lib.awtextra.AbsoluteConstraints(199, 314, 174, -1));
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-6, -10, 450, 320));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(View_Mayor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(View_Mayor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(View_Mayor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(View_Mayor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new View_Mayor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    public javax.swing.JButton jbtn_calcular;
    public javax.swing.JLabel jl_mayor;
    public javax.swing.JLabel jl_numero1;
    public javax.swing.JLabel jl_numero2;
    public javax.swing.JLabel jl_numero3;
    public javax.swing.JTextField jtf_mayor;
    public javax.swing.JTextField jtf_numero1;
    public javax.swing.JTextField jtf_numero2;
    public javax.swing.JTextField jtf_numero3;
    // End of variables declaration//GEN-END:variables
}
